const assert=require('node:assert/strict');
const {matches}=require('../web/criteria-filters.js');
const fields=[{id:'screen',type:'choice'},...Object.entries({rev_growth_qoq:10,gross_margin:25,pb_ratio:2,ps_ratio:2,pfcf_ratio:18,perf_year:0,debt_eq:2.5}).map(([metric,value])=>({id:'screen_'+metric,metric,type:'threshold',default:value})),{id:'price',type:'number'},{id:'verdict',type:'choice'},{id:'obv',type:'choice'}];
const cat={fields};
const stock=data=>({filter_values:data});
assert(matches(stock({price:100}),{},cat));
assert(!matches(stock({}),{price:{op:'min',value:0}},cat));
assert(matches(stock({}),{price:{op:'missing'}},cat));
assert(!matches(stock({price:0}),{price:{op:'missing'}},cat));
assert(matches(stock({price:100}),{price:{op:'max',value:100}},cat));
assert(matches(stock({rev_growth_qoq:10}),{screen:'quality_growth'},cat));
assert(!matches(stock({rev_growth_qoq:10,gross_margin:24}),{screen:'quality_growth'},cat));
assert(matches(stock({pb_ratio:1,ps_ratio:99,perf_year:-10}),{screen:'deep_value'},cat));
assert(!matches(stock({pfcf_ratio:-1,perf_year:-10}),{screen:'deep_value'},cat));
assert(!matches(stock({pb_ratio:1,perf_year:-10,debt_eq:3}),{screen:'deep_value'},cat));
assert(matches(stock({pb_ratio:1,perf_year:-10,debt_eq:3}),{screen:'deep_value',screen_debt_eq:4},cat));
assert(!matches(stock({}),{screen:'either'},cat));
const original=stock({verdict:'Watch',obv:'yes'});
assert(!matches(original,{verdict:'Buy'},cat));
assert(matches(original,{obv:'yes'},cat));
assert.equal(original.filter_values.verdict,'Watch');
console.log('Criteria filter logic: 14 checks passed');
