const assert=require('node:assert/strict');
const {settings,baseMatch,match}=require('../web/screening-lab.js');
const base={cap:300,price:1,liquidity:10,sector:''};
const stock=metrics=>({sector:'Technology',metrics:{market_cap:300e6,price:10,avg_dollar_volume:10e6,...metrics}});
assert(baseMatch(stock({}),base));
assert(!baseMatch(stock({market_cap:299e6}),base));
assert(!baseMatch(stock({avg_dollar_volume:null}),base));
assert(baseMatch(stock({avg_dollar_volume:null}),{...base,liquidity:0}));
assert(!baseMatch(stock({}),{...base,sector:'Consumer Cyclical'}));
const expensive=stock({rev_growth_qoq:-5,pb_ratio:10,ps_ratio:10,pfcf_ratio:40,perf_year:-20,debt_eq:1});
assert(!match(expensive,settings({},'current')));
assert(match(expensive,settings({},'basic')));
assert(match(expensive,settings({},'no_multiples')));
assert(!match(stock({...expensive.metrics,debt_eq:4}),settings({},'no_multiples')));
assert(!match(stock({...expensive.metrics,perf_year:5}),settings({},'value_no_multiples')));
const bookCheap=stock({...expensive.metrics,pb_ratio:1});
assert(match(bookCheap,settings({},'current')));
assert(!match(bookCheap,settings({},'no_pb_ps')));
assert(match(stock({rev_growth_qoq:10,gross_margin:null}),settings({},'current')));
assert(!match(stock({rev_growth_qoq:10,gross_margin:20}),settings({},'current')));
const custom=settings({},'value_no_multiples');custom.rules.perf_year.enabled=false;custom.rules.debt_eq.enabled=false;
assert(match(stock({}),custom));
assert.equal(settings({deep_value:{pfcf_max:22}},'current').rules.pfcf_ratio.value,22);
console.log('Screening Lab: 16 checks passed');
